### ISSUE TITLE
Trouble building with cm-11.0

### ISSUE THREAD

**Issue by jbonhag** [CMyst/android_device_htc_mystul#1]
Hi,

I'm having trouble building CM with this device tree.  I initialized my repo with:

```
repo init -u https://github.com/CyanogenMod/android.git -b cm-11.0
```

Then, I created a local manifest under `.repo/local_manifests/mystul.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <project name="CMyst/android_device_htc_mystul" path="device/htc/mystul" remote="github" revision="cm-11.0"/>
</manifest>
```

I ran `repo sync` and I can see everything under `device/htc/mystul`.  When I run `source build/envsetup.sh`, I can see that the device tree is getting pulled in:

```
...
including device/htc/mystul/vendorsetup.sh
....
```

but I don't see any `mystul` choices under `breakfast`, `brunch`, or `lunch`.  I assume that it would add `cm_mystul-userdebug` and `cm_mystul-eng`.

Could someone please help me get pointed in the right direction?

**Comment by natekc** [comment]
you can just type it in, even if it doesn't show up in lunch/brunch/etc
Just type:

. build/envsetup.sh && lunch cm_mystul-eng
mka bacon

**Comment by natekc** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2353225/10990759/979da522-840b-11e5-94fa-3622ab98e90c.png)
It works fine for me.  let me know if you need any more help compiling/building.

**Comment by jbonhag** [comment]
@jianC Yes!  Thank you so much.  I got it to build by following the instructions in https://github.com/CMyst/android.  I've got a nice collection of .img files now but can't seem to flash my phone -- fastboot is giving me errors like "99 unknown error".

**Comment by natekc** [comment]
That's because fastboot won't accept large images like system.img (not sure why).  You will have to flash recovery.img first,  then sideload the resulting .zip package through recovery.  Make sure to backup everything on your phone onto your computer because you will have to factory reset to flash cm11.  If you are not s-off, you will also have to flash boot.img after flashing the zip.

**Comment by jbonhag** [comment]
I did it!  I got into recovery, formatted all my partitions and then re-flashed everything with:

```
for img in *.img; do eval $(echo fastboot flash ${img/img/} $img | sed 's/\.//'); done
```

```
sending 'boot' (5886 KB)...
OKAY [  0.917s]
writing 'boot'...
OKAY [  1.480s]
finished. total time: 2.398s
sending 'ramdisk-recovery' (3647 KB)...
OKAY [  0.631s]
writing 'ramdisk-recovery'...
(bootloader) signature checking...
FAILED (remote: signature verify fail)
finished. total time: 1.054s
sending 'ramdisk' (363 KB)...
OKAY [  0.238s]
writing 'ramdisk'...
(bootloader) signature checking...
FAILED (remote: signature verify fail)
finished. total time: 0.283s
sending 'recovery' (9170 KB)...
OKAY [  1.095s]
writing 'recovery'...
OKAY [  2.194s]
finished. total time: 3.289s
sending 'system' (415418 KB)...
OKAY [ 14.875s]
writing 'system'...
OKAY [ 92.241s]
finished. total time: 107.117s
```

Now I'm happily tapping away in Cyanogenmod.  Thank you so much for your help!

**Comment by jianC** [comment]
No problem!  Let me know if you find any issues (there's bound to be).
